import type { GroupingRule } from "./rule-schema";

export const defaultGroupingRules: GroupingRule[] = [
  {
    id: "primary-with-children",
    name: "带小朋友优先",
    kind: "PRIMARY",
    enabled: true,
    priority: 600,
    conditions: { all: [{ fact: "childCount", operator: "greaterThan", value: 0 }] },
    targetGroupKey: "family-with-children",
  },
  {
    id: "primary-out-of-town",
    name: "远道宾客优先",
    kind: "PRIMARY",
    enabled: true,
    priority: 500,
    conditions: { all: [{ fact: "isOutOfTown", operator: "equal", value: true }] },
    targetGroupKey: "out-of-town",
  },
  {
    id: "primary-groom",
    name: "男方亲友",
    kind: "PRIMARY",
    enabled: true,
    priority: 400,
    conditions: { all: [{ fact: "relation", operator: "in", value: ["GROOM_RELATIVE", "GROOM_FRIEND"] }] },
    targetGroupKey: "groom-guests",
  },
  {
    id: "primary-bride",
    name: "女方亲友",
    kind: "PRIMARY",
    enabled: true,
    priority: 300,
    conditions: { all: [{ fact: "relation", operator: "in", value: ["BRIDE_RELATIVE", "BRIDE_FRIEND"] }] },
    targetGroupKey: "bride-guests",
  },
  {
    id: "primary-mutual",
    name: "共同好友",
    kind: "PRIMARY",
    enabled: true,
    priority: 200,
    conditions: { all: [{ fact: "relation", operator: "in", value: ["MUTUAL_FRIEND", "COLLEAGUE", "CLASSMATE"] }] },
    targetGroupKey: "mutual-friends",
  },
  {
    id: "primary-other",
    name: "其他宾客",
    kind: "PRIMARY",
    enabled: true,
    priority: 100,
    conditions: { all: [{ fact: "relation", operator: "equal", value: "OTHER" }] },
    targetGroupKey: "other-guests",
  },
  {
    id: "tag-with-children",
    name: "标签：带小朋友",
    kind: "TAG",
    enabled: true,
    priority: 600,
    conditions: { all: [{ fact: "childCount", operator: "greaterThan", value: 0 }] },
    targetTagKey: "with-children",
  },
  {
    id: "tag-out-of-town",
    name: "标签：外地宾客",
    kind: "TAG",
    enabled: true,
    priority: 500,
    conditions: { all: [{ fact: "isOutOfTown", operator: "equal", value: true }] },
    targetTagKey: "out-of-town",
  },
  {
    id: "tag-groom",
    name: "标签：男方亲友",
    kind: "TAG",
    enabled: true,
    priority: 400,
    conditions: { all: [{ fact: "relation", operator: "in", value: ["GROOM_RELATIVE", "GROOM_FRIEND"] }] },
    targetTagKey: "groom-side",
  },
  {
    id: "tag-bride",
    name: "标签：女方亲友",
    kind: "TAG",
    enabled: true,
    priority: 300,
    conditions: { all: [{ fact: "relation", operator: "in", value: ["BRIDE_RELATIVE", "BRIDE_FRIEND"] }] },
    targetTagKey: "bride-side",
  },
  {
    id: "tag-colleague",
    name: "标签：同事",
    kind: "TAG",
    enabled: true,
    priority: 200,
    conditions: { all: [{ fact: "relation", operator: "equal", value: "COLLEAGUE" }] },
    targetTagKey: "colleague",
  },
  {
    id: "tag-classmate",
    name: "标签：同学",
    kind: "TAG",
    enabled: true,
    priority: 100,
    conditions: { all: [{ fact: "relation", operator: "equal", value: "CLASSMATE" }] },
    targetTagKey: "classmate",
  },
];
